### PR TITLE
Fix when visual editor URL is relative (missing http://)

### LINKED ISSUE #1376: Visual editor: autocomplete non-http-prepended URLs
### Description of Feature

It's very common to enter URLs without prepending http:// or https://, like so:

image

Instead of autocompletion, GrowthBook instead shows a mysterious error, which could be extremely discouraging to new users:

Screenshot 2023-06-20 at 8 53 42 AM

This is a confusing breakpoint in a key workflow for first-time users. At minimum it should have some common causes of the "There was a problem loading the experiment"; ideally, it should attempt to correct URLs in formats that won't work out of the box.

### PR DESCRIPTION
**Pull request by jdorn**
### Features and Changes

Trims and prepends `http://` to relative visual editor URLs in the "Open Visual Editor" button.

Fixes #1376

### CODE REVIEW

File: packages/front-end/components/OpenVisualEditorLink.tsx [hunk 1]
```diff
@@ -27,21 +27,33 @@ const OpenVisualEditorLink: FC<{
...
   }, [visualEditorUrl, id, changeIndex, apiHost]);
 
   return (
     <>
-      <span
+      <a
+        href={url}
         className="btn btn-sm btn-primary"
         onClick={async (e) => {
+          e.preventDefault();
```
Comment (bttf) [inline packages/front-end/components/OpenVisualEditorLink.tsx:55]: Will changing to an anchor tag and removing `preventDefault` circumvent the checks we have implemented inside the `onClick` handler?

Comment (jdorn) [reply packages/front-end/components/OpenVisualEditorLink.tsx:55]: It the user right clicks and opens in a new tab, it will bypass the extension check and tracking calls. I was mostly thinking about the experience if you are using a dev build of the chrome extension. The extension check will fail, and it would be nice if there was an easy way to bypass it without modifying code. Open to other ideas. Maybe in the extension modal we can add a small link to continue anyway?

I have a feeling I do have a bug there right now when URL is empty. Need to test this some more.

**Review by bttf — APPROVED** [review]
