### PR TITLE
Fix whitespace bug with saved groups

### LINKED ISSUE #1605: [Bug] Switching to raw text mode adds extra space in front of each token in comma-separated list for saved groups.
### Summary
When editing saved groups with existing comma-separated list of tokens, switching to raw text mode, and adding additional elements, adds an extra space in front of each token. This space is saved into the token. 

#### Expected Behavior

Switching to raw text mode should not add extra space in front of the token. 

#### Current Behavior

(1) Existing comma-separated list contains 2 elements:
image

(2) Switching to raw text mode adds an extra space in front of each token
image

(3a) Adding another element in raw text mode...
image

(3b)...adds the extra space into existing tokens
image

### PR DESCRIPTION
**Pull request by msamper**
### Features and Changes

Fixes bug that adds whitespace to the beginning of values for a saved group

- Closes #1605 

### Testing

1. Create a saved group
2. Add some values & save
3. Edit the group in raw text mode & save
4. Check audit log for saved group and make sure the change only added the new value and didn't add whitespaces to the previously existing values

### CODE REVIEW

File: packages/front-end/components/SavedGroupForm.tsx [hunk 1]
```diff
@@ -88,7 +88,10 @@ const SavedGroupForm: FC<{
           value={rawText}
           onChange={(e) => {
             setRawText(e.target.value);
-            form.setValue("groupList", e.target.value.trim().split(","));
```
Comment (msamper) [inline packages/front-end/components/SavedGroupForm.tsx:91]: I was trimming the beginning and end of the entire CSV string instead of the individual values

**Review by jdorn — APPROVED** [review]
