### PR TITLE
Visual Experiments - Add EditDOMMutations modal

### LINKED ISSUE #1393: [Bug] Visual Editor - Custom JS - Redirects cause the visual editor to be inaccessible
### Summary

Adding redirect code to a visual experiment variation via the Custom JS feature will render the visual editor inaccessible due to the navigation to a new page. There is currently no way to remove the Custom JS once it has been added.

#### Expected Behavior

A way to undo a user's custom JS if it leads them to a broken state.

#### Current Behavior

There is no way to undo Custom JS changes outside of the Visual Editor.

### PR DESCRIPTION
**Pull request by bttf**
This is a simple modal available on the Experiments page that allows a user to delete 1. Global CSS 2. Custom JS or 3. Any single DOM mutation from a variation in their Visual Experiment

Closes #1393 

## Screenshots
Screenshot 2023-06-23 at 12 54 01 PM

Screenshot 2023-06-23 at 12 54 04 PM
Screenshot 2023-06-23 at 12 54 10 PM
Screenshot 2023-06-23 at 12 54 14 PM
Screenshot 2023-06-23 at 12 54 20 PM

### CODE REVIEW

File: packages/front-end/components/Experiment/EditDOMMutationsModal.tsx [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+const EditDOMMutatonsModal: FC<{
+  visualChange: VisualChange;
+  close: () => void;
+  onSave: (newVisualChange: VisualChange) => void;
+}> = ({ close, visualChange, onSave }) => {
+  const [newVisualChange, setNewVisualChange] = useState<VisualChange>(
+    visualChange
+  );
+
+  const deleteCustomJS = useCallback(() => {
```
Comment (bryce-fitzsimons) [inline packages/front-end/components/Experiment/EditDOMMutationsModal.tsx:15]: nit: useCallback for these seems unnecessary, as it's a very inexpensive operation

File: packages/front-end/components/Experiment/EditDOMMutationsModal.tsx [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+      cta="Save"
+    >
+      <div className="col">
+        <div className="mb-4">
+          <h4>
+            Global CSS
+            {newVisualChange.css ? (
+              <small className="ml-2">
+                <a href="#" className="text-danger" onClick={deleteGlobalCSS}>
+                  delete
```
Comment (bryce-fitzsimons) [inline packages/front-end/components/Experiment/EditDOMMutationsModal.tsx:61]: I suppose it's the nature of an MVP escape hatch, but having only "delete" in an edit modal feels a bit odd. I think we could at least change the UI a tiny bit here.

Currently it looks visually like:
`1. delete`
... which visually implies that the title of the change is "delete". Maybe delete should be some sort of "x" or trash icon floating on the right instead?

File: packages/front-end/components/Experiment/EditDOMMutationsModal.tsx (hunk 1 above)
Comment (bttf) [reply packages/front-end/components/Experiment/EditDOMMutationsModal.tsx:15]: That's fair. It comes from a force of habit. I don't equate `useCallback`  as a thing to use when something is expensive but rather when 'we don't need to redefine this function per render'

File: packages/front-end/components/Experiment/VariationsTable.tsx [hunk 3]
```diff
@@ -373,10 +414,19 @@ const VariationsTable: FC<Props> = ({
                             return (
                               <td key={j} className="px-4 py-1">
                                 <div className="d-flex justify-content-between">
-                                  <div>
+                                  <a
```
Comment (bryce-fitzsimons) [inline packages/front-end/components/Experiment/VariationsTable.tsx:417]: Personal preference, but feels like this should be an edit button / pencil. Otherwise it's a lot of blue text under each changeset in the variations table.

**Comment by bttf** [comment]
Thanks @bryce-fitzsimons Largely agree with your feedback. I've updated the UI as follows, let me know what you think

1. Pencil icon Screenshot 2023-06-27 at 7 55 08 PM


3. Better delete links  Screenshot 2023-06-27 at 7 55 32 PM

File: packages/front-end/components/Experiment/EditDOMMutationsModal.tsx (hunk 2 above)
Comment (bttf) [reply packages/front-end/components/Experiment/EditDOMMutationsModal.tsx:61]: Addressed

**Comment by bttf** [comment]
Also added this
image

File: packages/front-end/components/Experiment/EditDOMMutationsModal.tsx [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+                  language="json"
+                  code={JSON.stringify(m)}
+                  className="disabled"
+                />
+                <button
+                  className="btn text-danger"
+                  onClick={() => deleteDOMMutation(i)}
+                  style={{ fontSize: "1.2rem", paddingLeft: "0.3rem" }}
+                >
+                  &times;
```
Comment (bryce-fitzsimons) [inline packages/front-end/components/Experiment/EditDOMMutationsModal.tsx:115]: IMO this one looks out of place compared to the other delete links

Comment (bryce-fitzsimons) [reply packages/front-end/components/Experiment/EditDOMMutationsModal.tsx:115]: Complicated! But good enough I think.

**Review by bryce-fitzsimons — APPROVED** [review]
lgtm
