### PR TITLE
Fixed date off by one in graph

### LINKED ISSUE #1065: [Bug] Date Dimension displaying incorrect dates on the chart compared to query detail
### Summary

When looking at the date dimension chart within an experiment analysis the dates are displaying incorrectly compared in the values shown by "view queries"
#### Expected Behavior

Dates in the chart should reflect the correct dates
#### Current Behavior

The dates display is 1 day less than it should be (March 6th is showing as March 6th)
chart

table

### PR DESCRIPTION
**Pull request by gazzdingo**
### Features and Changes

- Closes #1065

### CODE REVIEW

File: packages/front-end/components/Experiment/DateResults.tsx [hunk 1]
```diff
@@ -95,7 +97,9 @@ const DateResults: FC<{
 
     const sortedResults = [...results];
     sortedResults.sort((a, b) => {
-      return getValidDate(a.name).getTime() - getValidDate(b.name).getTime();
+      return (
+        getValidDateUTC(a.name).getTime() - getValidDateUTC(b.name).getTime()
```
Comment (lukesonnet) [inline packages/front-end/components/Experiment/DateResults.tsx:101]: It's probably actually not needed in these sort function (here and above in L70) since it'll just be doing extra offsetting to both dates. But it doesn't matter.

**Review by lukesonnet — CHANGES_REQUESTED** [review]
This doesn't actually work for `DateGraph` because the metric analysis object actually stores the dates as `Date` in the backend, so you end up correcting it on the front-end in some ways but then you get things like the dots and the line not matching up (see where the dot is): 

Screenshot 2023-12-04 at 3 52 19 PM

So I think we also need to add the UTC method to L56 of MetricAnalysisQueryRunner.ts in the back-end. I think you could probably then remove it from L190 of DateGraph.tsx (although IDK if they'd stack).

File: packages/front-end/components/Experiment/DateResults.tsx (hunk 1 above)
Comment (gazzdingo) [reply packages/front-end/components/Experiment/DateResults.tsx:101]: cool i can remove it from here and l70

**Review by lukesonnet — APPROVED** [review]
lgtm!
