### PR TITLE
Fix: Catch uncaught promise rejection when trying to connect to mongo

### LINKED ISSUE #28: Expose `role` in Snowflake setup
`role` was left out of the snowflake integration.

### PR DESCRIPTION
**Pull request by JonathanWolfe**
Adds `role` to the snowflake setup params

### CODE REVIEW

File: packages/back-end/src/app.ts [hunk 1]
```diff
@@ -68,7 +68,12 @@ async function init() {
       await queueInit();
     })();
   }
-  await initPromise;
+  try {
+    await initPromise;
+  } catch (err) {
+    console.error(err);
+    process.exit(1);
```
Comment (JonathanWolfe) [inline packages/back-end/src/app.ts:75]: This was an uncaught promise rejection when mongo wasn't turned on

**Comment by jdorn** [comment]
Sorry, didn't notice you were working on this.  I saw the issue you made and already pushed a fix to main (6721cc7).  

I see you found an uncaught Mongo exception too.  If you update the PR with just that change I can merge it.

**Comment by JonathanWolfe** [comment]
> 
> 
> Sorry, didn't notice you were working on this. I saw the issue you made and already pushed a fix to main ([6721cc7](https://github.com/growthbook/growthbook/commit/6721cc779a84b43440f82596f5f91e9623af700b)).
> 
> I see you found an uncaught Mongo exception too. If you update the PR with just that change I can merge it.

Haha, no worries. You'll want to squash these commits though.
