### PR TITLE
'View Queries' link for failed queries - Allow custom CTA for ViewAsyncQueriesButton

### LINKED ISSUE #811: [Feature] Smarter SQL error viewing
When you have an error with your SQL, it tells you to 'view the queries' to see the error. But this link to see the query can be in a few different places, depending on what page you're on, or the previous sql state. 

Screen Shot 2022-12-07 at 1 23 23 AM

It would be best to just link to view the error directly from the message, and have that link open the view queries modal.

### PR DESCRIPTION
**Pull request by bttf**
Closes #811 

I could only find two instances where we present an error message with a 'View Queries' prompt (metric details page, import experiments modal) ... Let me know if there are any others I may have missed

Screen Shot 2022-12-23 at 3 27 10 PM

Screen Shot 2022-12-23 at 3 27 22 PM

Screen Shot 2022-12-23 at 3 27 36 PM

Screen Shot 2022-12-23 at 3 27 38 PM

### CODE REVIEW

File: packages/front-end/components/Experiment/ImportExperimentList.tsx [hunk 1]
```diff
@@ -213,7 +213,22 @@ const ImportExperimentList: FC<{
...
               </p>
             )}
-            <span>View Queries (below) for more information.</span>
+            <span>
+              <ViewAsyncQueriesButton
+                queries={
+                  data.experiments.queries?.length > 0
+                    ? data.experiments.queries.map((q) => q.query)
+                    : []
+                }
```
Comment (vczb) [inline packages/front-end/components/Experiment/ImportExperimentList.tsx:222]: hello :wave: 

maybe we can improve this algotithm

the map always return a empty array if it has no length.

example 1:

```js
[].map(q => q.query)
// will return []
```

example 2:

```js
const data = {
    experiments: {
        queries: []
    }
}

data.experiments.queries.map(q => q.query)
// will return []
```

---

it means that you don't need do the ternary operator. 

```js
queries={data.experiments.queries.map((q) => q.query)}
```

probably will work fine. please, test if works as expected before update you code.

---

_ps: also you can create a memoization with [useMemo](https://beta.reactjs.org/reference/react/useMemo) to improve the performance. *ignore* if you arent familiar with react hooks_



thanks you :)

Comment (bttf) [reply packages/front-end/components/Experiment/ImportExperimentList.tsx]: Sure, addressed

**Review by tinahollygb — APPROVED** [review]
