### PR TITLE
Various fixes and improvements with the connection info for BIgQuery

### LINKED ISSUE #1569: [Bug] Unable to edit connection info without providing key again
The data source connection 'edit connection' modal requires adding the JSON key again for BigQuery data types, even if you don't plan on changing it.

### PR DESCRIPTION
**Pull request by Auz**
- Made the required input on the BigQuery form not required when editing. (Fixes #1569)
- Adjusted wording around project id and datasets. 
- Simplified code in the informationSchema.ts and added additional checks to make sure .tables is not undefined
- Added margin around the edit project icon.

### CODE REVIEW

File: packages/back-end/src/services/informationSchema.ts [hunk 1]
```diff
@@ -34,7 +34,12 @@ export function getRecentlyDeletedTables(
       if (!schema.tables) return;
       schema.tables.forEach((table) => {
         // If this table has an id, then it exists in the informationSchemaTables collection
-        if (table.id) {
+        if (
+          table.id &&
+          updatedInformationSchema[correspondingIndex].schemas[
+            correspondingSchemaIndex
+          ].tables
```
Comment (jdorn) [inline packages/back-end/src/services/informationSchema.ts:41]: Does this always exist?  Do we need null coalesces here?

**Review by jdorn — APPROVED** [review]
