### PR TITLE
fix(phases-dates): Format phase start/end time in UTC

### LINKED ISSUE #4478: [Bug] datetime and date in phase selector don't match
### Summary

If the time in the phase editor is in the first 6 hours of a day, the date that truncates the time shows it as the previous day, likely due to some time zone error.

Image

Image

### PR DESCRIPTION
**Pull request by ahdriel**
### Features and Changes

Fixes #4478

When editing the phase, the datepicker correctly shows the time in UTC and it gets saved in Mongo also in UTC.
But when showing in the UI we are converting from UTC to the user's local time, leading to confusion.

So now we format the timestamp in the UTC timezone as well to ensure the values match.

https://www.loom.com/share/8e3b4dd171ad487eaf3b4e84a9e48879

### CODE REVIEW

**Review by lukesonnet — CHANGES_REQUESTED** [review]
Thanks Adriel. Can you also fix the date used in the analysis settings bar? You can see it on the loom next to the update button.

It may be worth it to check for other usages of `date` on the experiment page or even in the experiments list.

**Comment by ahdriel** [comment]
@lukesonnet Good catch!

I searched for places where we use phase `dateStarted` & `dateEnded` and fixed the ones I found.

File: packages/front-end/components/DataViz/SqlExplorerDataVisualization.tsx [hunk 1]
```diff
@@ -464,6 +464,12 @@ export function DataVisualizationDisplay({
                 color: textColor,
               },
               top: "bottom",
+              formatter: (name: string) => {
```
Comment (lukesonnet) [inline packages/front-end/components/DataViz/SqlExplorerDataVisualization.tsx]: intentional?

Comment (ahdriel) [reply packages/front-end/components/DataViz/SqlExplorerDataVisualization.tsx]: not at all -- leftover from a code review.

**Review by lukesonnet — APPROVED** [review]
For some of these we may want to make it clear the date is UTC (e.g. the timelines) but I think being consistent is more important so this lgtm.

File: packages/shared/src/dates.ts [hunk 2]
```diff
@@ -5,14 +5,23 @@ import differenceInHours from "date-fns/differenceInHours";
 import addMonths from "date-fns/addMonths";
 import formatRelative from "date-fns/formatRelative";
 import previousMonday from "date-fns/previousMonday";
+import { formatInTimeZone } from "date-fns-tz";
 
-export function date(date: string | Date): string {
+export function date(date: string | Date, inTimezone?: string): string {
```
Comment (ahdriel) [inline packages/shared/src/dates.ts:10]: FWIW, if we upgrade to date-fns v4 a lot of this is built-in -- but that's a bigger project that should be done separately.
