### PR TITLE
Coalesce null aggregate metric values to fix stats bugs

### LINKED ISSUE #725: [Bug] Incorrect experiment results when metrics contain `null` values
### Summary

If a metric value contains `null`s for some users, they will be ignored when doing `mean` and `stddev` in SQL, but will be included when doing `count`.  There are places in our code where we calculate the "sum" as `mean * count`, which will be incorrect in this case and cause our statistics engine to give incorrect results.

To solve, in the `__userMetric` CTE, we should use coalesce:

```sql
SELECT
  d.variation,
  d.dimension,
  d.${baseIdType},
  coalesce(${aggregate}, 0) as value
```

### PR DESCRIPTION
**Pull request by jdorn**
### Features and Changes

When metric values contain `null`, it can cause unpredictable results in our stats engine.  Most aggregate functions ignore nulls (e.g. `SUM(value)`), but `COUNT(*)` does not.  So you get into a weird situation where `COUNT(*) * AVG(value)` does not equal `SUM(value)`.

In addition, when using ratio metrics, having null values can cause impossible covariance matrices and negative variance.

This PR uses `coalesce` to turn nulls into `0` before passing into aggregate and statistical functions.

Fixes #725

### CODE REVIEW

**Review by bryce-fitzsimons — COMMENTED** [review]
Looks good to me

**Review by bryce-fitzsimons — DISMISSED** [review]

**Review by bryce-fitzsimons — APPROVED** [review]

File: packages/back-end/src/integrations/SqlIntegration.ts [hunk 1]
```diff
@@ -399,8 +399,8 @@ export default abstract class SqlIntegration
             SELECT
               date,
               COUNT(*) as count,
-              ${this.avg("value")} as mean,
-              ${this.stddev("value")} as stddev
+              ${this.avg("coalesce(value,0)")} as mean,
```
Comment (lukesonnet) [inline packages/back-end/src/integrations/SqlIntegration.ts:402]: Because _byDateOverall and _overall are both downstream of `_metric` and we only do inner joins between them, wouldn't just changing L360 to be `coalesce(${aggregate, 0)` be a one line change that removes the need for these lines?

Seems like either approach should work, just wondering.

File: packages/back-end/src/integrations/SqlIntegration.ts [hunk 2]
```diff
@@ -1014,16 +1009,19 @@ export default abstract class SqlIntegration
...
-          ${this.variance("m.value")} as m_var,
+          ${this.avg("coalesce(m.value,0)")} as m_mean,
+          ${this.variance("coalesce(m.value,0)")} as m_var,
           ${this.ensureFloat("sum(m.value)")} as m_sum
           ${
             isRatio
               ? `,
-            ${this.avg("d.value")} as d_mean,
-            ${this.variance("d.value")} as d_var,
+            ${this.avg("coalesce(d.value,0)")} as d_mean,
```
Comment (lukesonnet) [inline packages/back-end/src/integrations/SqlIntegration.ts:1018]: If we make the above one line edit, and we keep this `LEFT JOIN` for ratio metrics, then we only need coalesce on the m.values, not on the d.values. Of course, if we change to `FULL OUTER JOIN` for ratio metrics, then we would need both coalesce statements.

**Review by lukesonnet — COMMENTED** [review]
In general, this looks good to me! Just asked a question about where we do the COALESCE.

File: packages/back-end/src/integrations/SqlIntegration.ts (hunk 2 above)
Comment (jdorn) [reply packages/back-end/src/integrations/SqlIntegration.ts:1018]: Yeah, I didn't want to rely on the specific joins we're using today since that is likely to change in the future.
