### PR TITLE
Fixed bug with the Add Data Source Modal when component re-renders. 

### LINKED ISSUE #535: [Bug] Can't add matomo data source
Hello,

great that you added matomo to the data sources!

I tried to add a new data source based on the new predefined type (and not on a custom connection).

But I get an error when I want to save the "matomo query options":

Cannot use 'in' operator to search for 'defaultSchema' in undefined

I get this error online at https://app.growthbook.io/.

Any ideas how to solve this? 

Best regards,

Timo

image

### PR DESCRIPTION
**Pull request by Auz**
### Features and Changes

- Switching away from the Add Data Source Modal, causes the component to re-render and lose the form state of what datasource the user is editing or updating. Removed useEffect entirely to prevent this. 
- Made the whole div clickable when expanding the 'Show All' when selecting event trackers
- Fixed edge case error state when phase is not defined

Fixes #535

### CODE REVIEW

File: packages/front-end/services/utils.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export function phaseSummary(
   return (
     <>
       <span className="phase">
-        {phase.phase === "main" ? "" : phase.phase + ", "}
+        {phase?.phase === "main" || !phase?.phase ? "" : phase.phase + ", "}
```
Comment (jdorn) [inline packages/front-end/services/utils.tsx:21]: If `phase` is undefined, this whole function should just return `null` immediately.

**Review by jdorn — APPROVED** [review]
