### PR TITLE
Webhooks tweaks: Added force for lost experiments, and always return groups if set.

### LINKED ISSUE #159: Webhooks return data for force and groups that's unexpected.
When an experiment is stopped, flagging it as 'Winner', the remote config properly returns the property 'force' for this stopped experiment, specifying the variation ID that won. But for all other results (Lost, Did not finish, Inconclusive) there is not force: O on the remote config. At least we should set the force state for 'Lost' 

Also groups are only returned in the webhook when the experiment in running state. Users may still want to deliver the appropriate variation to the groups when in other states, particularly 'lost'.

### PR DESCRIPTION
**Pull request by Auz**
Fixes #159

### CODE REVIEW

File: packages/back-end/src/controllers/config.ts [hunk 1]
```diff
@@ -157,7 +152,7 @@ export async function getExperimentsScript(
       }
 
       if (exp.status === "stopped") {
-        if (exp.results === "won") {
+        if (exp.results === "won" || exp.results === "lost") {
```
Comment (gozup) [inline packages/back-end/src/controllers/config.ts:155]: Hi @Auz ,

Don't you think that if the experiment have lost, `data.force` should equal `0` instead of `exp.winner` ?

```typescript
if (exp.status === "stopped") {
    if (exp.results === "won") {
        data.force = exp.winner;
    } else if (exp.results === "lost") {
        data.force = 0;
    } else {
       return;
    }
}
```

Best,
Manu

Comment (Auz) [reply packages/back-end/src/controllers/config.ts:155]: winner is set to 0 in the case of a loss (which isn't great naming). My concern was about making the assumption that 0 was always the control.

Comment (gozup) [reply packages/back-end/src/controllers/config.ts:155]: Make sense. Thanks for the details.

Comment (Auz) [reply packages/back-end/src/controllers/config.ts]: Thinking more about it we agree with you. 0 (control) should be returned for all other experiment results.
